# Generated by Django 4.0 on 2022-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_date_posted_post_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.TextField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
